timeout: 3
serial: yes
interface_branding: Tunix
interface_branding_colour: 4
interface_resolution: 1280x720
wallpaper: boot():/boot/wallpaper.png
wallpaper_style: stretched
backdrop: 1a1b26
term_background: 401a1b26
term_foreground: c0caf5
term_background_bright: 414868
term_foreground_bright: f4f7ff
term_palette: 15161e;f7768e;9ece6a;e0af68;7aa2f7;bb9af7;7dcfff;c0caf5
term_palette_bright: 414868;ff899d;b9f27c;f4c97a;8db0ff;c7a9ff;9be8ff;f4f7ff
term_margin: 64
term_margin_gradient: 20

/Tunix
    protocol: linux
    resolution: 1280x720
    path: boot():/boot/Image
    cmdline: root=LABEL=tunix-root

/Tunix (one processor)
    protocol: linux
    resolution: 1280x720
    path: boot():/boot/Image
    cmdline: root=LABEL=tunix-root nosmp

/Tunix (shell)
    protocol: linux
    resolution: 1280x720
    path: boot():/boot/Image
    cmdline: root=LABEL=tunix-root init=/bin/sh verbose

/Tunix (hardware report)
    protocol: linux
    resolution: 1280x720
    path: boot():/boot/Image
    cmdline: root=LABEL=tunix-root hwreport
