timeout: 10
serial: yes

/Tunix hardware report
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: root=LABEL=tunix-root hwreport nv50

/Tunix hardware report (acpi mode)
    protocol: limine
    path: boot():/boot/kernel.elf
    cmdline: root=LABEL=tunix-root hwreport nv50 acpi_button=on
